# Generated by Django 4.1.4 on 2022-12-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="ownder",
            new_name="owner",
        ),
    ]
